train_args:
  num_epochs: 100
  learning_rate: 1.0e-4
  weight_decay: 0
  warmup_steps: 200 
  cooldown_steps: null
  checkpoint: null
<<<<<<< HEAD:src/contrastors/configs/train/pa-100k/nomic_pa-100k.yaml
  wandb: false
=======
  wandb: True
>>>>>>> parent of f0c4ccb (增加教师蒸馏部分):src/contrastors/configs/train/nomic_pa-100k.yaml
  wandb_project_name: "nomic"
  wandb_entity: "yuesang"
  wandb_run_name: "PA-100k-emov2-2m"
  profile: false
  log_grads_every: 100
  log_lr_every: 10
  save_every: 25000
  eval_steps: 1000
  eval_strategy: "epochs"
  chunk_size: 1536
  # output_dir: "ckpts/facebook/dino-vits8"
  output_dir: "ckpts/person/pa-100k/emov2-2m_teacher"
  # if using deepspeed, this will be ignored
  schedule_type: "cosine"
  max_grad_norm: 1.0
  adam_beta1: 0.9
  adam_beta2: 0.95
  grad_cache: false
  loss_fn: "clip"
  add_l2_loss: false
  pretrained: null
  pooling: "last"
  use_fp8: false
  clamp_logits: false 
  logit_max: 100

data_args:
  image_text_shards: "/data/yuesang/LLM/contrastors/data/pa100k_label/train.json"
  eval_flickr: false
  # (TODO): zanussbaum up workers and check deterministic
  workers: 8 
  # this is per gpu batch size
<<<<<<< HEAD:src/contrastors/configs/train/pa-100k/nomic_pa-100k.yaml
  batch_size: 256
  eval_batch_size: 256
=======
  batch_size: 2048
  eval_batch_size: 2048
>>>>>>> parent of f0c4ccb (增加教师蒸馏部分):src/contrastors/configs/train/nomic_pa-100k.yaml
  seed: 42
  shuffle: false
  imagenet_val_path: "/data/yuesang/LLM/contrastors/data/test/test.json"
  dataset_resampled: false
  is_local: true

model_args:
  model_type: "locked_text"

text_model_args:
  model_type: "locked_text"
  seq_len: 77
  model_name: "/data/yuesang/LLM/VectorIE/models/nomic/nomic-embed-text-v1.5"
  tokenizer_name: "/data/yuesang/LLM/VectorIE/models/nomic/nomic-embed-text-v1.5"
  pooling: "mean"
  freeze: true
  add_prefix: true
  projection_dim: null
  nomic_encoder: true
  pretrained: true
  ema: false
  precomputed: false
  hamming: true

vision_model_args:
  model_type: "locked_text"
  model_name: "EMO2_2M_k5_hybrid"
  pretrained: true
  pooling: "none"
  freeze: false
  nomic_encoder: false
  logit_scale: null
  trainable_logit_scale: true
  gradient_checkpointing: false
  projection_dim: 768
<<<<<<< HEAD:src/contrastors/configs/train/pa-100k/nomic_pa-100k.yaml
  distill_type: ""

=======
>>>>>>> parent of f0c4ccb (增加教师蒸馏部分):src/contrastors/configs/train/nomic_pa-100k.yaml

transforms:
  image_size: 224


classiffer_config:
  open: True
  classes: {
        Female: {
            nc: 2,
            text_en: {
                no: "the person is not female",
                yes: "the person is female"
            }
        },
        AgeOver60: {
            nc: 2,
            text_en: {
                no: "the person does not appear to be over 60 years old",
                yes: "the person appears to be over 60 years old"
            }
        },
        Age18-60: {
            nc: 2,
            text_en: {
                no: "the person does not appear to be between 18 and 60 years old",
                yes: "the person appears to be between 18 and 60 years old"
            }
        },
        AgeLess18: {
            nc: 2,
            text_en: {
                no: "the person does not appear to be under 18 years old",
                yes: "the person appears to be under 18 years old"
            }
        },
        Front: {
            nc: 2,
            text_en: {
                no: "the person is not facing the camera",
                yes: "the person is facing the camera"
            }
        },
        Side: {
            nc: 2,
            text_en: {
                no: "the person is not viewed from the side",
                yes: "the person is viewed from the side"
            }
        },
        Back: {
            nc: 2,
            text_en: {
                no: "the person is not facing away from the camera",
                yes: "the person is facing away from the camera"
            }
        },
        Hat: {
            nc: 2,
            text_en: {
                no: "the person is not wearing a hat",
                yes: "the person is wearing a hat"
            }
        },
        Glasses: {
            nc: 2,
            text_en: {
                no: "the person is not wearing glasses",
                yes: "the person is wearing glasses"
            }
        },
        HandBag: {
            nc: 2,
            text_en: {
                no: "the person is not carrying a handbag",
                yes: "the person is carrying a handbag"
            }
        },
        ShoulderBag: {
            nc: 2,
            text_en: {
                no: "the person is not carrying a shoulder bag",
                yes: "the person is carrying a shoulder bag"
            }
        },
        Backpack: {
            nc: 2,
            text_en: {
                no: "the person is not carrying a backpack",
                yes: "the person is carrying a backpack"
            }
        },
        HoldObjectsInFront: {
            nc: 2,
            text_en: {
                no: "the person is not holding objects in front",
                yes: "the person is holding objects in front"
            }
        },
        ShortSleeve: {
            nc: 2,
            text_en: {
                no: "the person is not wearing short sleeves",
                yes: "the person is wearing short sleeves"
            }
        },
        LongSleeve: {
            nc: 2,
            text_en: {
                no: "the person is not wearing long sleeves",
                yes: "the person is wearing long sleeves"
            }
        },
        UpperStride: {
            nc: 2,
            text_en: {
                no: "the person's upper clothing does not have stripes",
                yes: "the person's upper clothing has stripes"
            }
        },
        UpperLogo: {
            nc: 2,
            text_en: {
                no: "the person's upper clothing does not have a logo",
                yes: "the person's upper clothing has a logo"
            }
        },
        UpperPlaid: {
            nc: 2,
            text_en: {
                no: "the person's upper clothing is not plaid",
                yes: "the person's upper clothing is plaid"
            }
        },
        UpperSplice: {
            nc: 2,
            text_en: {
                no: "the person's upper clothing is not spliced",
                yes: "the person's upper clothing is spliced"
            }
        },
        LowerStripe: {
            nc: 2,
            text_en: {
                no: "the person's lower clothing does not have stripes",
                yes: "the person's lower clothing has stripes"
            }
        },
        LowerPattern: {
            nc: 2,
            text_en: {
                no: "the person's lower clothing does not have a pattern",
                yes: "the person's lower clothing has a pattern"
            }
        },
        LongCoat: {
            nc: 2,
            text_en: {
                no: "the person is not wearing a long coat",
                yes: "the person is wearing a long coat"
            }
        },
        Trousers: {
            nc: 2,
            text_en: {
                no: "the person is not wearing trousers",
                yes: "the person is wearing trousers"
            }
        },
        Shorts: {
            nc: 2,
            text_en: {
                no: "the person is not wearing shorts",
                yes: "the person is wearing shorts"
            }
        },
        Skirt&Dress: {
            nc: 2,
            text_en: {
                no: "the person is not wearing a skirt or dress",
                yes: "the person is wearing a skirt or dress"
            }
        },
        boots: {
            nc: 2,
            text_en: {
                no: "the person is not wearing boots",
                yes: "the person is wearing boots"
            }
        },
        ublack: {
            nc: 2,
            text_en: {
                no: "the person's upper clothing is not black",
                yes: "the person's upper clothing is black"
            }
        },
        ugray: {
            nc: 2,
            text_en: {
                no: "the person's upper clothing is not gray",
                yes: "the person's upper clothing is gray"
            }
        },
        ublue: {
            nc: 2,
            text_en: {
                no: "the person's upper clothing is not blue",
                yes: "the person's upper clothing is blue"
            }
        },
        ugreen: {
            nc: 2,
            text_en: {
                no: "the person's upper clothing is not green",
                yes: "the person's upper clothing is green"
            }
        },
        uwhite: {
            nc: 2,
            text_en: {
                no: "the person's upper clothing is not white",
                yes: "the person's upper clothing is white"
            }
        },
        upurple: {
            nc: 2,
            text_en: {
                no: "the person's upper clothing is not purple",
                yes: "the person's upper clothing is purple"
            }
        },
        ured: {
            nc: 2,
            text_en: {
                no: "the person's upper clothing is not red",
                yes: "the person's upper clothing is red"
            }
        },
        ubrown: {
            nc: 2,
            text_en: {
                no: "the person's upper clothing is not brown",
                yes: "the person's upper clothing is brown"
            }
        },
        uyellow: {
            nc: 2,
            text_en: {
                no: "the person's upper clothing is not yellow",
                yes: "the person's upper clothing is yellow"
            }
        },
        upink: {
            nc: 2,
            text_en: {
                no: "the person's upper clothing is not pink",
                yes: "the person's upper clothing is pink"
            }
        },
        uorange: {
            nc: 2,
            text_en: {
                no: "the person's upper clothing is not orange",
                yes: "the person's upper clothing is orange"
            }
        },
        ubeige: {
            nc: 2,
            text_en: {
                no: "the person's upper clothing is not beige",
                yes: "the person's upper clothing is beige"
            }
        },
        ustriped_color: {
            nc: 2,
            text_en: {
                no: "the person's upper clothing is not striped",
                yes: "the person's upper clothing is striped"
            }
        },
        umulticolor: {
            nc: 2,
            text_en: {
                no: "the person's upper clothing is not multicolored",
                yes: "the person's upper clothing is multicolored"
            }
        },
        lwhite: {
            nc: 2,
            text_en: {
                no: "the person's lower clothing is not white",
                yes: "the person's lower clothing is white"
            }
        },
        lpink: {
            nc: 2,
            text_en: {
                no: "the person's lower clothing is not pink",
                yes: "the person's lower clothing is pink"
            }
        },
        lred: {
            nc: 2,
            text_en: {
                no: "the person's lower clothing is not red",
                yes: "the person's lower clothing is red"
            }
        },
        lgreen: {
            nc: 2,
            text_en: {
                no: "the person's lower clothing is not green",
                yes: "the person's lower clothing is green"
            }
        },
        lyellow: {
            nc: 2,
            text_en: {
                no: "the person's lower clothing is not yellow",
                yes: "the person's lower clothing is yellow"
            }
        },
        lpurple: {
            nc: 2,
            text_en: {
                no: "the person's lower clothing is not purple",
                yes: "the person's lower clothing is purple"
            }
        },
        lbrown: {
            nc: 2,
            text_en: {
                no: "the person's lower clothing is not brown",
                yes: "the person's lower clothing is brown"
            }
        },
        lblack: {
            nc: 2,
            text_en: {
                no: "the person's lower clothing is not black",
                yes: "the person's lower clothing is black"
            }
        },
        lorange: {
            nc: 2,
            text_en: {
                no: "the person's lower clothing is not orange",
                yes: "the person's lower clothing is orange"
            }
        },
        lblue: {
            nc: 2,
            text_en: {
                no: "the person's lower clothing is not blue",
                yes: "the person's lower clothing is blue"
            }
        },
        lgray: {
            nc: 2,
            text_en: {
                no: "the person's lower clothing is not gray",
                yes: "the person's lower clothing is gray"
            }
        },
        lbeige: {
            nc: 2,
            text_en: {
                no: "the person's lower clothing is not beige",
                yes: "the person's lower clothing is beige"
            }
        },
        lstriped_color: {
            nc: 2,
            text_en: {
                no: "the person's lower clothing is not striped",
                yes: "the person's lower clothing is striped"
            }
        },
        lmulticolor: {
            nc: 2,
            text_en: {
                no: "the person's lower clothing is not multicolored",
                yes: "the person's lower clothing is multicolored"
            }
        }

  }
