train_args:
  num_epochs: 200
  learning_rate: 1.0e-3
  weight_decay: 0
  warmup_steps: 200 
  cooldown_steps: null
  checkpoint: null
  wandb: True
  wandb_project_name: "peta-vits"
  wandb_entity: "yuesang"
  wandb_run_name: "peta-vits"
  profile: false
  log_grads_every: 100
  log_lr_every: 10
  save_every: 25000
  eval_steps: 1000
  eval_strategy: "epochs"
  chunk_size: 1536
  # output_dir: "ckpts/facebook/dino-vits8"
  output_dir: "ckpts/person/peta/vits"
  # if using deepspeed, this will be ignored
  schedule_type: "cosine"
  max_grad_norm: 1.0
  adam_beta1: 0.9
  adam_beta2: 0.95
  grad_cache: false
  loss_fn: "clip"
  add_l2_loss: false
  pretrained: null
  pooling: "last"
  use_fp8: false
  clamp_logits: false 
  logit_max: 100

data_args:
  image_text_shards: "/data/yuesang/LLM/contrastors/data/PETA/train_peta.json"
  eval_flickr: false
  # (TODO): zanussbaum up workers and check deterministic
  workers: 8 
  # this is per gpu batch size
  batch_size: 512
  eval_batch_size: 512
  seed: 42
  shuffle: false
  imagenet_val_path: "/data/yuesang/LLM/contrastors/data/PETA/val_peta.json"
  dataset_resampled: false
  is_local: true

model_args:
  model_type: "locked_text"

text_model_args:
  model_type: "locked_text"
  seq_len: 77
  model_name: "/data/yuesang/LLM/VectorIE/models/nomic/nomic-embed-text-v1.5"
  tokenizer_name: "/data/yuesang/LLM/VectorIE/models/nomic/nomic-embed-text-v1.5"
  pooling: "mean"
  freeze: true
  add_prefix: true
  projection_dim: null
  nomic_encoder: true
  pretrained: true
  ema: false
  precomputed: false
  hamming: true

vision_model_args:
  model_type: "locked_text"
  model_name: "nomic-ai/vit_eva02_base_patch16_224.mim_in22k"
  pretrained: true
  pooling: "map"
  freeze: false
  nomic_encoder: false
  logit_scale: null
  trainable_logit_scale: true
  gradient_checkpointing: true
  projection_dim: 768

transforms:
  image_size: 224


classiffer_config:
  open: True
  classes: {
        accessoryHeadphone: {
            nc: 2,
            text_en: {
                no: "the person is not wearing headphones",
                yes: "the person is wearing headphones"
            }
        },
        personalLess15: {
            nc: 2,
            text_en: {
                no: "the person does not appear to be younger than 15",
                yes: "the person appears to be younger than 15"
            }
        },
        personalLess30: {
            nc: 2,
            text_en: {
                no: "the person does not appear to be younger than 30",
                yes: "the person appears to be younger than 30"
            }
        },
        personalLess45: {
            nc: 2,
            text_en: {
                no: "the person does not appear to be younger than 45",
                yes: "the person appears to be younger than 45"
            }
        },
        personalLess60: {
            nc: 2,
            text_en: {
                no: "the person does not appear to be younger than 60",
                yes: "the person appears to be younger than 60"
            }
        },
        personalLarger60: {
            nc: 2,
            text_en: {
                no: "the person does not appear to be older than 60",
                yes: "the person appears to be older than 60"
            }
        },
        carryingBabyBuggy: {
            nc: 2,
            text_en: {
                no: "the person is not carrying a baby buggy",
                yes: "the person is carrying a baby buggy"
            }
        },
        carryingBackpack: {
            nc: 2,
            text_en: {
                no: "the person is not carrying a backpack",
                yes: "the person is carrying a backpack"
            }
        },
        hairBald: {
            nc: 2,
            text_en: {
                no: "the person is not bald",
                yes: "the person is bald"
            }
        },
        footwearBoots: {
            nc: 2,
            text_en: {
                no: "the person is not wearing boots",
                yes: "the person is wearing boots"
            }
        },
        lowerBodyCapri: {
            nc: 2,
            text_en: {
                no: "the person is not wearing capri pants",
                yes: "the person is wearing capri pants"
            }
        },
        carryingOther: {
            nc: 2,
            text_en: {
                no: "the person is not carrying anything else",
                yes: "the person is carrying something else"
            }
        },
        carryingShoppingTro: {
            nc: 2,
            text_en: {
                no: "the person is not carrying a shopping trolley",
                yes: "the person is carrying a shopping trolley"
            }
        },
        carryingUmbrella: {
            nc: 2,
            text_en: {
                no: "the person is not carrying an umbrella",
                yes: "the person is carrying an umbrella"
            }
        },
        lowerBodyCasual: {
            nc: 2,
            text_en: {
                no: "the person is not wearing casual lower-body clothing",
                yes: "the person is wearing casual lower-body clothing"
            }
        },
        upperBodyCasual: {
            nc: 2,
            text_en: {
                no: "the person is not wearing casual upper-body clothing",
                yes: "the person is wearing casual upper-body clothing"
            }
        },
        personalFemale: {
            nc: 2,
            text_en: {
                no: "the person is not female",
                yes: "the person is female"
            }
        },
        carryingFolder: {
            nc: 2,
            text_en: {
                no: "the person is not carrying a folder",
                yes: "the person is carrying a folder"
            }
        },
        lowerBodyFormal: {
            nc: 2,
            text_en: {
                no: "the person is not wearing formal lower-body clothing",
                yes: "the person is wearing formal lower-body clothing"
            }
        },
        upperBodyFormal: {
            nc: 2,
            text_en: {
                no: "the person is not wearing formal upper-body clothing",
                yes: "the person is wearing formal upper-body clothing"
            }
        },
        accessoryHairBand: {
            nc: 2,
            text_en: {
                no: "the person is not wearing a hair band",
                yes: "the person is wearing a hair band"
            }
        },
        accessoryHat: {
            nc: 2,
            text_en: {
                no: "the person is not wearing a hat",
                yes: "the person is wearing a hat"
            }
        },
        lowerBodyHotPants: {
            nc: 2,
            text_en: {
                no: "the person is not wearing hot pants",
                yes: "the person is wearing hot pants"
            }
        },
        upperBodyJacket: {
            nc: 2,
            text_en: {
                no: "the person is not wearing a jacket",
                yes: "the person is wearing a jacket"
            }
        },
        lowerBodyJeans: {
            nc: 2,
            text_en: {
                no: "the person is not wearing jeans",
                yes: "the person is wearing jeans"
            }
        },
        accessoryKerchief: {
            nc: 2,
            text_en: {
                no: "the person is not wearing a kerchief",
                yes: "the person is wearing a kerchief"
            }
        },
        footwearLeatherShoes: {
            nc: 2,
            text_en: {
                no: "the person is not wearing leather shoes",
                yes: "the person is wearing leather shoes"
            }
        },
        upperBodyLogo: {
            nc: 2,
            text_en: {
                no: "the person is not wearing upper-body clothing with a logo",
                yes: "the person is wearing upper-body clothing with a logo"
            }
        },
        hairLong: {
            nc: 2,
            text_en: {
                no: "the person does not have long hair",
                yes: "the person has long hair"
            }
        },
        lowerBodyLongSkirt: {
            nc: 2,
            text_en: {
                no: "the person is not wearing a long skirt",
                yes: "the person is wearing a long skirt"
            }
        },
        upperBodyLongSleeve: {
            nc: 2,
            text_en: {
                no: "the person is not wearing long sleeves",
                yes: "the person is wearing long sleeves"
            }
        },
        lowerBodyPlaid: {
            nc: 2,
            text_en: {
                no: "the person is not wearing plaid lower-body clothing",
                yes: "the person is wearing plaid lower-body clothing"
            }
        },
        lowerBodyThinStripes: {
            nc: 2,
            text_en: {
                no: "the person is not wearing thin-striped lower-body clothing",
                yes: "the person is wearing thin-striped lower-body clothing"
            }
        },
        carryingLuggageCase: {
            nc: 2,
            text_en: {
                no: "the person is not carrying a luggage case",
                yes: "the person is carrying a luggage case"
            }
        },
        personalMale: {
            nc: 2,
            text_en: {
                no: "the person is not male",
                yes: "the person is male"
            }
        },
        carryingMessengerBag: {
            nc: 2,
            text_en: {
                no: "the person is not carrying a messenger bag",
                yes: "the person is carrying a messenger bag"
            }
        },
        accessoryMuffler: {
            nc: 2,
            text_en: {
                no: "the person is not wearing a muffler",
                yes: "the person is wearing a muffler"
            }
        },
        accessoryNothing: {
            nc: 2,
            text_en: {
                no: "the person is wearing some accessories",
                yes: "the person is not wearing any accessories"
            }
        },
        carryingNothing: {
            nc: 2,
            text_en: {
                no: "the person is carrying something",
                yes: "the person is not carrying anything"
            }
        },
        upperBodyNoSleeve: {
            nc: 2,
            text_en: {
                no: "the person is not wearing no-sleeve upper-body clothing",
                yes: "the person is wearing no-sleeve upper-body clothing"
            }
        },
        upperBodyPlaid: {
            nc: 2,
            text_en: {
                no: "the person is not wearing plaid upper-body clothing",
                yes: "the person is wearing plaid upper-body clothing"
            }
        },
        carryingPlasticBags: {
            nc: 2,
            text_en: {
                no: "the person is not carrying plastic bags",
                yes: "the person is carrying plastic bags"
            }
        },
        footwearSandals: {
            nc: 2,
            text_en: {
                no: "the person is not wearing sandals",
                yes: "the person is wearing sandals"
            }
        },
        footwearShoes: {
            nc: 2,
            text_en: {
                no: "the person is not wearing shoes",
                yes: "the person is wearing shoes"
            }
        },
        hairShort: {
            nc: 2,
            text_en: {
                no: "the person does not have short hair",
                yes: "the person has short hair"
            }
        },
        lowerBodyShorts: {
            nc: 2,
            text_en: {
                no: "the person is not wearing shorts",
                yes: "the person is wearing shorts"
            }
        },
        upperBodyShortSleeve: {
            nc: 2,
            text_en: {
                no: "the person is not wearing short sleeves",
                yes: "the person is wearing short sleeves"
            }
        },
        lowerBodyShortSkirt: {
            nc: 2,
            text_en: {
                no: "the person is not wearing a short skirt",
                yes: "the person is wearing a short skirt"
            }
        },
        footwearSneaker: {
            nc: 2,
            text_en: {
                no: "the person is not wearing sneakers",
                yes: "the person is wearing sneakers"
            }
        },
        footwearStocking: {
            nc: 2,
            text_en: {
                no: "the person is not wearing stockings",
                yes: "the person is wearing stockings"
            }
        },
        upperBodyThinStripes: {
            nc: 2,
            text_en: {
                no: "the person is not wearing thin-striped upper-body clothing",
                yes: "the person is wearing thin-striped upper-body clothing"
            }
        },
        upperBodySuit: {
            nc: 2,
            text_en: {
                no: "the person is not wearing a suit",
                yes: "the person is wearing a suit"
            }
        },
        carryingSuitcase: {
            nc: 2,
            text_en: {
                no: "the person is not carrying a suitcase",
                yes: "the person is carrying a suitcase"
            }
        },
        lowerBodySuits: {
            nc: 2,
            text_en: {
                no: "the person is not wearing lower-body suit clothing",
                yes: "the person is wearing lower-body suit clothing"
            }
        },
        accessorySunglasses: {
            nc: 2,
            text_en: {
                no: "the person is not wearing sunglasses",
                yes: "the person is wearing sunglasses"
            }
        },
        upperBodySweater: {
            nc: 2,
            text_en: {
                no: "the person is not wearing a sweater",
                yes: "the person is wearing a sweater"
            }
        },
        upperBodyThickStripes: {
            nc: 2,
            text_en: {
                no: "the person is not wearing thick-striped upper-body clothing",
                yes: "the person is wearing thick-striped upper-body clothing"
            }
        },
        lowerBodyTrousers: {
            nc: 2,
            text_en: {
                no: "the person is not wearing trousers",
                yes: "the person is wearing trousers"
            }
        },
        upperBodyTshirt: {
            nc: 2,
            text_en: {
                no: "the person is not wearing a T-shirt",
                yes: "the person is wearing a T-shirt"
            }
        },
        upperBodyOther: {
            nc: 2,
            text_en: {
                no: "the person is not wearing other upper-body clothing",
                yes: "the person is wearing other upper-body clothing"
            }
        },
        upperBodyVNeck: {
            nc: 2,
            text_en: {
                no: "the person is not wearing a V-neck top",
                yes: "the person is wearing a V-neck top"
            }
        }



        # footwear: {
        #     nc: 11,
        #     text_en: {
        #         Black: "the footwear is black",
        #         Blue: "the footwear is blue",
        #         Brown: "the footwear is brown",
        #         Green: "the footwear is green",
        #         Grey: "the footwear is grey",
        #         Orange: "the footwear is orange",
        #         Pink: "the footwear is pink",
        #         Purple: "the footwear is purple",
        #         Red: "the footwear is red",
        #         White: "the footwear is white",
        #         Yellow: "the footwear is yellow"
        #     }
        # },
        # hair: {
        #     nc: 11,
        #     text_en: {
        #         Black: "the hair is black",
        #         Blue: "the hair is blue",
        #         Brown: "the hair is brown",
        #         Green: "the hair is green",
        #         Grey: "the hair is grey",
        #         Orange: "the hair is orange",
        #         Pink: "the hair is pink",
        #         Purple: "the hair is purple",
        #         Red: "the hair is red",
        #         White: "the hair is white",
        #         Yellow: "the hair is yellow"
        #     }
        # },
        # lowerbody: {
        #     nc: 11,
        #     text_en: {
        #         Black: "the lower-body clothing is black",
        #         Blue: "the lower-body clothing is blue",
        #         Brown: "the lower-body clothing is brown",
        #         Green: "the lower-body clothing is green",
        #         Grey: "the lower-body clothing is grey",
        #         Orange: "the lower-body clothing is orange",
        #         Pink: "the lower-body clothing is pink",
        #         Purple: "the lower-body clothing is purple",
        #         Red: "the lower-body clothing is red",
        #         White: "the lower-body clothing is white",
        #         Yellow: "the lower-body clothing is yellow"
        #     }
        # },
        # upperbody: {
        #     nc: 11,
        #     text_en: {
        #         Black: "the upper-body clothing is black",
        #         Blue: "the upper-body clothing is blue",
        #         Brown: "the upper-body clothing is brown",
        #         Green: "the upper-body clothing is green",
        #         Grey: "the upper-body clothing is grey",
        #         Orange: "the upper-body clothing is orange",
        #         Pink: "the upper-body clothing is pink",
        #         Purple: "the upper-body clothing is purple",
        #         Red: "the upper-body clothing is red",
        #         White: "the upper-body clothing is white",
        #         Yellow: "the upper-body clothing is yellow"
        #     }
        # }

  }
